### ISSUE TITLE
Si un audio dura menos de un min se ponen solo los segundos

### ISSUE THREAD

**Issue by daniihc16** [UNIZAR-30226-2024-03/unizar-30226-2024-03.github.io#169]
Dark Mystery Trailer dura 48 y aparece 48 en lugar de 00:48

**Comment by Arejula11** [comment]
Arreglado.
![image](https://github.com/UNIZAR-30226-2024-03/unizar-30226-2024-03.github.io/assets/92888725/8240ec8d-4457-4ed9-9f37-3b071c3f1608)
