### ISSUE TITLE
Error en página artist

### ISSUE THREAD

**Issue by Arejula11** [UNIZAR-30226-2024-03/unizar-30226-2024-03.github.io#27]
En el carrousel de discografia hay que quitar el titulo y la flecha.

![Image](https://github.com/UNIZAR-30226-2024-03/Web/assets/92888725/51aa7a7b-f8a1-487e-b831-36b39924e2f0)

**Comment by pabloangusto** [comment]
Y no es mejor poner el titulo: todos, y luego una pagina con todos los singles y albumes. En el carrousel solo poner 10 o asi y los demas en la otra pagina.

**Comment by Arejula11** [comment]
Me refiero que en el componente carrousel no aparezca el para ti ni la flecha, porque si se quiere utilizar en otra página e igual no se necesita el titulo y la flecha como es en el caso del panel de creador. Respecto a lo tuyo si, eso es lo que tenía pensado, por eso existe la flecha, para que te lleve a una página con todo lo demás, de hecho en algunos ya tiene link a otra página para simular esa acción
