### ISSUE TITLE
Estadísticas en el dashboard

### ISSUE THREAD

**Issue by Arejula11** [UNIZAR-30226-2024-03/unizar-30226-2024-03.github.io#43]
Se han puesto únicamente contadores para las tres estadísticas, no todas deben ser contadores. Al menos la de la reproducciones mensuales debe ser una gráfica con todas las reproducciones a lo largo de los meses. Por lo menos esa era la idea inicial.
<img width="1418" alt="image" src="https://github.com/UNIZAR-30226-2024-03/unizar-30226-2024-03.github.io/assets/92888725/2b24bc8e-a3ea-482c-afa1-769a86d4b4e4">

**Comment by pabloangusto** [comment]
Yo lo dejaria asi y si se quieren estadísticas con más información, se puede ir a la página de estadísticas que para eso está.

**Comment by Arejula11** [comment]
Pero entonces hay que cambiar los headings, porque no usuarios mensuales no tiene sentido que sea un numero. Por mi bien, lo dejamos asi pero hay que cambiarlos títulos.

**Comment by pabloangusto** [comment]
Me parece bien.
